
-- KURUMSAL YÖNETİM VE GELİŞİM DANIŞMANLIĞI
INSERT INTO services (title, description, icon, sort_order, is_active, created_at, updated_at) VALUES 
('Dijital Dönüşüm Danışmanlığı', 'İşletmelerin dijital teknolojileri benimsemesi ve dijital süreçlere geçiş yapması için stratejik planlama, teknoloji seçimi ve değişim yönetimi konularında kapsamlı danışmanlık hizmeti veriyoruz.', 'Smartphone', 38, 1, datetime('now'), datetime('now')),
('İnsan Kaynakları Yönetimi Danışmanlığı', 'Modern İK uygulamaları, performans yönetimi, yetenek geliştirme ve çalışan deneyimi optimizasyonu konularında stratejik İK danışmanlığı sunuyoruz.', 'Users', 39, 1, datetime('now'), datetime('now')),
('Pazarlama Yönetimi ve Marka Danışmanlığı', 'Marka stratejisi geliştirme, pazarlama karması optimizasyonu ve müşteri deneyimi yönetimi konularında bütünleşik pazarlama danışmanlığı hizmeti veriyoruz.', 'Megaphone', 40, 1, datetime('now'), datetime('now')),
('Süreç Analizi ve Yönetimi Danışmanlığı', 'İş süreçlerinin haritalanması, analiz edilmesi ve optimize edilmesi için sistematik yaklaşımlar geliştirerek operasyonel mükemmellik hedeflerine ulaşılmasını destekliyoruz.', 'GitBranch', 41, 1, datetime('now'), datetime('now')),
('Stratejik Satın Alma Danışmanlığı', 'Tedarik zinciri optimizasyonu, satın alma stratejileri geliştirme ve tedarikçi ilişkileri yönetimi konularında değer odaklı danışmanlık hizmeti sunuyoruz.', 'ShoppingCart', 42, 1, datetime('now'), datetime('now')),
('Stratejik Planlama ve Kurumsal Yönetim Danışmanlığı', 'Organizasyonel vizyon-misyon belirleme, stratejik hedef belirleme ve kurumsal yönetim ilkelerinin uygulanması konularında üst düzey yönetim danışmanlığı veriyoruz.', 'Map', 43, 1, datetime('now'), datetime('now')),
('Kalite Sistemleri Danışmanlığı', 'Kalite yönetim sistemlerinin tasarlanması, uygulanması ve sürekli iyileştirilmesi konusunda sektör deneyimimizi paylaşarak müşteri memnuniyetinin artırılmasını hedefliyoruz.', 'CheckCircle2', 44, 1, datetime('now'), datetime('now')),
('TURQUALITY Danışmanlığı', 'Türk markalarının uluslararası pazarlarda güçlenmesi için TURQUALITY destek programına başvuru süreçleri ve marka geliştirme stratejileri konusunda uzman danışmanlık sunuyoruz.', 'Flag', 45, 1, datetime('now'), datetime('now')),

-- İŞ SAĞLIĞI VE GÜVENLİĞİ DANIŞMANLIĞI
('Acil Durum ve Kriz Yönetimi', 'İşyerlerinde olası acil durumlar için hazırlık planları oluşturma, kriz yönetimi prosedürleri geliştirme ve acil müdahale ekiplerinin eğitimi konularında kapsamlı danışmanlık hizmeti veriyoruz.', 'AlertTriangle', 46, 1, datetime('now'), datetime('now')),
('Yangın Güvenliği Hizmeti', 'Yangın risk analizleri, yangın güvenlik sistemlerinin tasarlanması ve yangın önleme stratejilerinin geliştirilmesi konularında teknik uzmanlık ve danışmanlık hizmeti sunuyoruz.', 'Flame', 47, 1, datetime('now'), datetime('now')),
('Tahliye Planı Hazırlama', 'İşyeri tahliye planlarının hazırlanması, tahliye yollarının optimize edilmesi ve tahliye tatbikatlarının düzenlenmesi konularında yasal gereklilikler çerçevesinde hizmet veriyoruz.', 'Navigation', 48, 1, datetime('now'), datetime('now')),
('İş Kanunları Işığında İş Kazası Tatbikatı', 'İş kazası senaryolarına dayalı tatbikatlar düzenleyerek çalışanların farkındalığını artırma ve yasal yükümlülüklerin yerine getirilmesi konularında uygulamalı eğitim hizmeti sunuyoruz.', 'BookOpen', 49, 1, datetime('now'), datetime('now')),
('Kaza Araştırması ve Kök Sebep Analizi', 'İş kazalarının sistematik araştırılması, kök sebeplerin belirlenmesi ve tekrarlanmasını önleyici önlemlerin geliştirilmesi konularında bilimsel metodoloji uygulayarak çözüm önerileri sunuyoruz.', 'Search', 50, 1, datetime('now'), datetime('now')),
('Risk Analizi Hazırlama', 'İşyeri risk değerlendirmelerinin yapılması, mesleki risklerin belirlenmesi ve risk kontrol önlemlerinin geliştirilmesi konularında yasal gereklilikler doğrultusunda kapsamlı hizmet veriyoruz.', 'AlertCircle', 51, 1, datetime('now'), datetime('now')),
('ATEX - Patlamadan Korunma Dokümanı', 'Patlayıcı atmosferlerin bulunduğu işyerlerinde ATEX direktifleri kapsamında patlamadan korunma dokümanlarının hazırlanması ve güvenlik önlemlerinin belirlenmesi konularında uzman danışmanlık sunuyoruz.', 'Zap', 52, 1, datetime('now'), datetime('now')),
('Makine Risklerinin Yönetimi', 'Endüstriyel makinelerin güvenlik değerlendirmesi, makine güvenliği standartlarına uygunluk kontrolü ve makine risklerinin minimize edilmesi konularında teknik danışmanlık hizmeti veriyoruz.', 'Cog', 53, 1, datetime('now'), datetime('now')),
('Davranış Odaklı İSG Yönetimi', 'Güvenli davranışların geliştirilmesi için davranışsal güvenlik programlarının tasarlanması ve uygulanması konusunda çalışan katılımını önceleyen modern yaklaşımlar sunuyoruz.', 'Brain', 54, 1, datetime('now'), datetime('now'));
