name: Azure Static Web App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    # Sadece 'main' branch'ine push yapıldığında veya pull request açıldığında/güncellendiğinde çalışır.
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # ÖNEMLİ: Bu secret adının, GitHub'da oluşturduğunuz secret adıyla aynı olduğundan emin olun.
          # Önceki adımlarda "AZURE_STATIC_WEB_APPS_API_TOKEN" olarak oluşturmuştuk.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} 
          
          # Bu satır, pull request'ler için önizleme ortamları oluşturulmasını sağlar.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
          action: "upload"

          ###### Proje Yapılandırmanız ######
          # Projenizin kök dizininde Vite kodları olduğu için "/" kalmalı.
          app_location: "/"

          # Projenizde ayrı bir "api" klasörü olmadığı için boş bırakıyoruz.
          api_location: ""

          # Projeniz Vite kullandığı için derleme çıktıları "dist" klasöründedir.
          output_location: "dist"
          ####################################

  close_pull_request_job:
    # Bir pull request kapatıldığında, Azure'daki önizleme ortamını otomatik olarak siler.
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Bu satırın çalışabilmesi için de "azure_static_web_apps_api_token" secret'ının doğru olması gerekir.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
