name: Deploy to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Zip the function app (excluding dev folders)
      # DEĞİŞİKLİK: node_modules, .git ve .github klasörlerini zip dosyasına dahil etmiyoruz.
      # Bu, paketi küçültür ve daha temiz bir dağıtım sağlar.
      run: zip -r functionapp.zip . -x "node_modules/*" ".git/*" ".github/*"

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1.4.0
      with:
        app-name: renasportal
        package: functionapp.zip
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
