jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - run: zip -r release.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app

      - run: unzip release.zip -d app

      - uses: Azure/functions-action@v1
        with:
          app-name: 'renasportal'
          package: './app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DB3E459DEE3D4D45B8F05CA60B2DE19E }}
