name: Build and deploy Node.js project to Azure Function App - renasportal

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Projenin kök dizini
  NODE_VERSION: '22.x' # Node versiyonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip the project files for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'renasportal'
          package: './app'  # unzip edilen klasör burada
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DB3E459DEE3D4D45B8F05CA60B2DE19E }}
